Import libraries.

In [ ]:
import pip
import pandas as pd
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt
import math

Creating an transition matrix of Blake Snell's pitch-by-pitch data.
Left to right: fastball, changeup, curveball, slider.

In [ ]:
T=np.array([[0.372670807453416, 0.221238938053097, 0.402439024390244, 0.275510204081633], [0.180124223602484, 0.300884955752212, 0.26219512195122, 0.244897959183673], [0.285714285714286, 0.283185840707965, 0.195121951219512, 0.275510204081633], [0.161490683229814, 0.194690265486726, 0.140243902439024, 0.204081632653061]])
print(T)

[[0.37267081 0.22123894 0.40243902 0.2755102 ]
 [0.18012422 0.30088496 0.26219512 0.24489796]
 [0.28571429 0.28318584 0.19512195 0.2755102 ]
 [0.16149068 0.19469027 0.1402439  0.20408163]]


Initial vector of pitch distribution.

In [ ]:
v=np.array([0.25,0.25,0.25,0.25])
print(v)

[0.25 0.25 0.25 0.25]


Running the markov chain to the 100,000th power to determine the likelihood of a given pitch over the long-haul.

In [ ]:
print(np.dot(np.linalg.matrix_power(T,100000),v))

[0.32715597 0.24173497 0.25981771 0.17129135]
